"""priority not pripority

Revision ID: f0bad0cbbfd4
Revises: 23c4b4f26f63
Create Date: 2024-08-30 10:45:42.991094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bad0cbbfd4'
down_revision = '23c4b4f26f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=50), nullable=False))
        batch_op.drop_column('pripority')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pripority', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
